### ISSUE TITLE
Some series return None for their format

### ISSUE THREAD

**Issue by RossSmyth** [MajorWorkAlot/ALExport#1]
Hello, I attempted to use your script today and it almost worked fine except that some series return None for their 'format' type, specifically in my case "Senyoku no Sigrdrifa" returns None.

I fixed this by putting 
`if listentry['media']['format'] is not None else "TV"` 
in lines 147 and 171 but I'm not sure if that's how you would actually want to handle these errors, that's just how I did in my specific case.

**Comment by Tulla4U** [comment]
Ah this is a fun one, it's possible to update the mapping to include None. 

Question is what value should be used to replace it, I think MAL uses Unknown if the format hasn't been added, so I'll use that.
