### ISSUE TITLE
Error when media format is None

### ISSUE THREAD

**Issue by onlybrad** [MajorWorkAlot/ALExport#2]
Error message:

```
Traceback (most recent call last):
  File "ExportAnilist.py", line 143, in <module>
    etree.SubElement(anime, 'series_type').text = animeConversions[listentry['media']['format']]
KeyError: None
```

Culprit: The anime Kimi to Boku no Saigo no Senjou, Aruiwa Sekai ga Hajimaru Seisen (Zoku-hen). It's a sequel that was announced a while ago, no format was given to it.

{'score': 0, 'repeat': 0, 'progress': 0, 'notes': None, 'completedAt': {'year': None, 'month': None, 'day': None}, 'startedAt': {'year': None, 'month': None, 'day': None}, 'status': 'PLANNING', 'media': {'title': {'romaji': 'Kimi to Boku no Saigo no Senjou, Aruiwa Sekai ga Hajimaru Seisen (Zoku-hen)'}, 'idMal': 49981, 'id': 139825, **'format': None**, 'episodes': None}}

**Comment by Tulla4U** [comment]
Are you sure you are using the latest version? That case should be covered and I just exported my list with that entry on it. The line given in the Error also doesn't match the current version.

**Comment by onlybrad** [comment]
You are right, it turns out I was using an older version. No problem with the last version.
